name: Docs Build

on:
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the develop branch
  push:
    branches:
      - develop

jobs:
  docs-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps
        run: npm install

      - name: Build docs
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
